package:
  name: python-pcl
  version: 0.3.0

source:
  git_url: https://github.com/Sirokujira/python-pcl.git
  git_rev: c65905838bb6b089fde564cb6ecf6ceb7f8dee4f
  patches:
    - ext_args_win.patch                      [win]
    - dlls.patch                              [win]
    - ext_args_osx.patch                      [osx]
    - ext_args_linux.patch                    [linux]

build:
  number: 0                                   [win]
  number: 0                                   [osx]
  number: 0                                   [linux]
  has_prefix_files:                           [win]
    - Lib/site-packages/pcl/__init__.py       [win]

requirements:
  build:
    - python
    - cython        <=0.25.2
    - numpy
    - pkg-config                              [not win]
    - pcl           ==1.8.1
    - vtk           ==8.0.1
    - gcc                                     [not win]
    - nose
    - filelock
    - numpy
    - m2-patch                                [win]
    - vc 14                                   # [win and py>=35]
  run:
    - python
    - numpy
    - pcl           ==1.8.1
    - vtk           ==8.0.1
    - libgcc                                  [not win]
    - nose
    - filelock
    - numpy
    - vc 14                                   # [win and py>=35]

# test:
#   imports:
#     - pcl
#     - pcl.pcl_visualization

about:
  home: https://github.com/strawlab/python-pcl
  license: BSD
