package:
  name: vtk
  version: 8.0.1

source:
  url: https://github.com/Kitware/VTK/archive/v8.0.1.zip        [win64]
  fn:  vtk-8.0.1.zip                                            [win64]
  url: https://github.com/Kitware/VTK/archive/v8.0.1.tar.gz     [linux]
  fn:  vtk-8.0.1.tar.gz                                         [linux]
  url: https://github.com/Kitware/VTK/archive/v8.0.1.tar.gz     [osx]
  fn:  vtk-8.0.1.tar.gz                                         [osx]


build:
  number: 0
  msvc_compiler: 14.0


requirements:
  build:
    - cmake                       
    - vc 14                       # [win and py>=35]
  run:
    - vc 14                       # [win and py>=35]


# test:
#   imports:
#     - vtk

about:
  home: http://www.vtk.org/
  license: BSD
